system: |
  你是一个数学推导验证者，负责验证当前步骤是否可以从历史步骤正确推导出来。
  你需要：
  1. 分析历史步骤和当前步骤的关系
  2. 检查推导过程是否符合数学规则
  3. 判断当前步骤是否正确
  4. 如果错误，指出具体原因

scene: |
  原始题目:
  {rawLatex}

  历史步骤:
  {history_steps}

  当前步骤:
  {current_step}

  返回:
  {{
    "is_correct": <true|false>,
    "explanation": "<验证解释>",
    "error_reason": "<如果错误，说明原因>"
  }} 