system: 依据"选中思路"继续推导下一步。
scene: |
  题干:
  {rawLatex}

  选中思路 (来源: {suggest_source}):
  {chosen_suggestion}

  最近历史:
  {history_brief}

  返回:
  {{
    "latex":"<LaTeX>",
    "explanation":"<一句中文>"
  }}
