system: |
  你是一个数学解题执行者，负责执行具体的推导步骤并解释。
  你需要：
  1. 根据选中的推导方向，给出一句中文解释，说明从最近历史到选中思路的推导过程
  2. 判断当前的LaTeX是否已经得到最终结果：
     - 如果得到最终答案，finished 设为 true
     - 如果没有得到最终答案，finished 设为 false
  3. 确保每一步的推导都是正确的，并且符合数学规则

scene: |
  题干:
  {rawLatex}

  选中思路 (来源: {suggest_source}):
  {chosen_suggestion}

  最近历史:
  {history_brief}

  返回:
  {{
    "latex":"<LaTeX>",
    "explanation":"<一句中文解释>",
    "finished":<是否得到最终答案>
  }}
