"""init tables

Revision ID: a9757885287a
Revises: 
Create Date: 2025-05-09 02:02:03.984711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'a9757885287a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('problem',
    sa.Column('id', sa.UUID, nullable=False),
    sa.Column('rawLatex', sa.String, nullable=True),
    sa.Column('imageUrl', sa.String, nullable=True),
    sa.Column('audioUrl', sa.String, nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('block',
    sa.Column('id', sa.UUID, nullable=False),
    sa.Column('problemId', sa.UUID, nullable=False),
    sa.Column('orderIndex', sa.Integer(), nullable=False),
    sa.Column('latex', sa.String, nullable=False),
    sa.Column('html', sa.String, nullable=True),
    sa.Column('author', sa.String, nullable=False),
    sa.Column('isTerminal', sa.Boolean(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['problemId'], ['problem.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_block_orderIndex'), 'block', ['orderIndex'], unique=False)
    op.create_table('event',
    sa.Column('id', sa.UUID, nullable=False),
    sa.Column('problemId', sa.UUID, nullable=False),
    sa.Column('type', sa.String, nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['problemId'], ['problem.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event')
    op.drop_index(op.f('ix_block_orderIndex'), table_name='block')
    op.drop_table('block')
    op.drop_table('problem')
    # ### end Alembic commands ###
