# infra/docker-compose.yml
version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: mathcopilot_user
      POSTGRES_PASSWORD: mathcopilot_password
      POSTGRES_DB: mathcopilot_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 